name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.1.202
          username: user
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            cd /var/www/git-flow-new
            # Add any additional commands you want to run here
