name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: CD
        run: echo 'CD is Disabled (Check workflow comment for the code).'
      - name: Deploy using ssh
        uses: fifsky/ssh-action@master
        with:
            command: |
              cd /tmp
              ls -a
            host: ${{ secrets.HOST }}
            user: root
            key: ${{ secrets.PRIVATE_KEY}}
  
